title: BaseLib Wiki
description: Wiki for BaseLib, a mod for Slay the Spire 2.
theme: just-the-docs

url: https://alchyr.github.io/BaseLib-Wiki/

aux_links:
  BaseLib Repository: https://github.com/Alchyr/BaseLib-StS2
